### ISSUE TITLE
Add support for international language

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/youtube-uploader#10]
During login, choose the English (UK ) language, for the uploading script to work

Also, update the readme, and remove the unwanted language change requiremtns steps, as this will not be required and doesn't even work anyways

https://github.com/fawazahmed0/youtube-uploader/issues/12#issuecomment-873673001

**Comment by pierreminiggio** [comment]
Hello, I got the first lang switch to english working : https://github.com/fawazahmed0/youtube-uploader/pull/16
Working on changing again to english after loging in.  (Yes it turns back to french once I'm logged in...)

**Comment by pierreminiggio** [comment]
![image](https://user-images.githubusercontent.com/35456349/124523135-07f32280-ddf6-11eb-90da-98ff60346526.png)
Seems unrelated to my changes, it shows an incomplete link when the processing isn't done yet

**Comment by pierreminiggio** [comment]
![image](https://user-images.githubusercontent.com/35456349/124523288-c0b96180-ddf6-11eb-97bf-a404e3d5a225.png)
Fixed it with a simple do While
