### ISSUE TITLE
Script not ending after successfully uploading a video & console logs

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#104]
Hello ! I had to shutdown my automated uploads for the last few months, and I'm starting to get them back up and running again.

The video successfully uploads, but the process doesn't stop
![image](https://user-images.githubusercontent.com/35456349/170133024-379f9069-599c-4eb3-ad96-581759d3675e.png)

Haven't yet spent any time on this to trouble shoot at which point exactly it fails, hopefully I'll be able to free up some time later this week

And also, seems like we added console logs in that library.
It's great, but it pollutes the output, so if we want logs, we should probably set up a debug mode so that if we don't want to see them (and in my case, I don't), we can hide them.

**Comment by pierreminiggio** [comment]
Found a work around for my usecase to make up for these 2 issues, I forced the process to close after calling the fonction, and the logs stoped appearing as well.

I'll close the issue.

**Comment by fawazahmed0** [comment]
This should be fixed in the latest version
