### ISSUE TITLE
Who can help me?

### ISSUE THREAD

**Issue by Sen5ive** [fawazahmed0/youtube-uploader#106]
Who can help me to installing, and use this uploader?

**Comment by pierreminiggio** [comment]
Take a look at the [README.md](https://github.com/fawazahmed0/youtube-uploader/blob/main/README.md) file, everything is here 😁

**Comment by pierreminiggio** [comment]
And there are additional infos for NodeJS / npm beginners here : https://github.com/fawazahmed0/youtube-uploader/issues/84#issuecomment-1078432696
