### ISSUE TITLE
About the upload limit  x(

### ISSUE THREAD

**Issue by Sillco** [fawazahmed0/youtube-uploader#107]
First of all you guys did a wonderful job here everything runs smoothly when you use ts-node to run the script. 
But the upload limit still is the problem. 
I tried other approach like an api but still the upload limit is there. any ideas would be nice.
Again greate job <3.

**Comment by fawazahmed0** [comment]
https://github.com/fawazahmed0/youtube-uploader/issues/90#issuecomment-1194447374
