### ISSUE TITLE
How to make it post every 5 minutes ?

### ISSUE THREAD

**Issue by dori921** [fawazahmed0/youtube-uploader#108]
Hello.Im trying to do this by myself but i couldnt,Can anyone help me please ?

**Comment by dori921** [comment]
Hello.Thanks for your answer.
Im getting this error.
![image](https://user-images.githubusercontent.com/56732815/171974499-05f06d2c-e85c-4dc6-92c5-7eeaba90c67c.png)

**Comment by enmohsinali** [comment]
Opps missed an equal operator.

change this line 
```const startUploadingVideos () => { ```
to this
```const startUploadingVideos = () => { ```

**Comment by dori921** [comment]
Thanks a lot for your answers,I am getting errors again 
![image](https://user-images.githubusercontent.com/56732815/172055267-71cc3a79-55fe-4032-abfe-205dc1b4db80.png)

**Comment by dori921** [comment]
This is my full code.
`const { upload } = require('youtube-videos-uploader');
const credentials = { email: 'myemail@gmail.com', pass: 'mypassword' }




const videosFolder = "C:/Users/dori/Downloads/";
const startUploadingVideos = () => {
    fs.readdir(videosFolder, (err, files) => {
        files.forEach(file => {
            //if your folder also has other files then only upload the video files like mp4
            if(file.includes(".mp4")){
                videos_array.push({ 
                    path: destFolder+file,
                    title: 'Your video title here.',
                    description: 'Your video description here.',
                    onSuccess:onVideoUploadSuccess, skipProcessingWait: true, onProgress: (progress) => { console.log('progress', progress) }
                })
            }
        });
    });
    upload (credentials, videos_array, {headless:false}).then(console.log)
}

setInterval(startUploadingVideos,300000)`

**Comment by enmohsinali** [comment]
change destFolder with videosFolder to correctly set the path.
Rest of the code looks good.

**Comment by dori921** [comment]
Im having the same error :/

**Comment by enmohsinali** [comment]
You didn't imported the fs library
your full code should be

```
const { upload } = require('youtube-videos-uploader');
const credentials = { email: 'myemail@gmail.com', pass: 'mypassword' }
const fs = require('fs');




const videosFolder = "C:/Users/dori/Downloads/";
const startUploadingVideos = () => {
    fs.readdir(videosFolder, (err, files) => {
        files.forEach(file => {
            //if your folder also has other files then only upload the video files like mp4
            if(file.includes(".mp4")){
                videos_array.push({ 
                    path: videosFolder+file,
                    title: 'Your video title here.',
                    description: 'Your video description here.',
                    onSuccess:onVideoUploadSuccess, skipProcessingWait: true, onProgress: (progress) => { console.log('progress', progress) }
                })
            }
        });
    });
    upload (credentials, videos_array, {headless:false}).then(console.log)
}

setInterval(startUploadingVideos,300000)

```

**Comment by dori921** [comment]
![image](https://user-images.githubusercontent.com/56732815/172377875-9812f8cc-e746-4924-afd4-5ec443f1d043.png)
Im getting this one now

**Comment by dori921** [comment]
@r8u  i didn't asked you

**Comment by enmohsinali** [comment]
Hey @dori921  I am sorry to say @r8u said right.
You have to learn javascript first because these are basic errors.

Well.. define video_array on top of the function.

**Comment by dori921** [comment]
@enmohsinali Thanks a lot for your answers

**Comment by enmohsinali** [comment]
Your welcome.

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
