### ISSUE TITLE
I am getting timeout error

### ISSUE THREAD

**Issue by murqlegend** [fawazahmed0/youtube-uploader#110]
Hello guys, 

I am constantly getting timeout error, how can I get around it, I tried every way but I can't, what should I do?

![resim](https://user-images.githubusercontent.com/64785810/172913995-a0f7ae17-d979-4e6a-a6ac-951ac18931e9.png)

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
