### ISSUE TITLE
Stuck on upload process

### ISSUE THREAD

**Issue by dnlbbrg** [fawazahmed0/youtube-uploader#112]
Since YouTube seems to have changed their upload process the youtube uploader get stuck while uploading without any errors. Do you already know how to solve it?

**Comment by dominic-findlay** [comment]
Without seeing what the error message is?
It may be the same issue I am currently exp?

https://github.com/fawazahmed0/youtube-uploader/issues/114

**Comment by dnlbbrg** [comment]
I didn't get any errors, but the uploader is loosing the upload status when the process jumps from 100% directly into the processing.

**Comment by fawazahmed0** [comment]
This Should be fixed in latest version, please open a new issue if the issue still persists
