### ISSUE TITLE
How to upload 20 videos at once?

### ISSUE THREAD

**Issue by k3fjeee** [fawazahmed0/youtube-uploader#113]
Hello! 
How can I upload 20 videos at once, and not one at a time?

**Comment by wanghaisheng** [comment]
if you mean upload and edit metadata for 20 at the same time
make  no sense at all
just like your manually upload process, how can you do that

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
