### ISSUE TITLE
Issue running headless

### ISSUE THREAD

**Issue by dominic-findlay** [fawazahmed0/youtube-uploader#114]
I updated the version of the package (npm update) and it appears also updated the dependencies 

The error "TypeError: page._client.send is not a function" was happening when running it with headless :  true
When running it with headless : false this error is not occurring 

Probably related to this issue
https://github.com/berstend/puppeteer-extra/issues/651

I added this to my package.json with forces a lower version of puppeteer, which fixes this issue (for now),

  ```
  "overrides": {
    "puppeteer": "14.3.0"
  },
  ```

**Comment by fawazahmed0** [comment]
This Should be fixed in latest version, please open a new issue if the issue still persists
