### ISSUE TITLE
Caption Support

### ISSUE THREAD

**Issue by realtofuine** [fawazahmed0/youtube-uploader#117]
Is there support for captions? Just like when uploading videos, is there a way to specify a captions file (such as srt or vtt)?

**Comment by fawazahmed0** [comment]
Nope, but if someone has time, [this code](https://github.com/fawazahmed0/quran-videos/blob/main/hardcodesubv2.js#L698) has caption upload code , maybe someone can refer that to add caption support in this package

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
