### ISSUE TITLE
Couldn't sign you in 

### ISSUE THREAD

**Issue by dnlbbrg** [fawazahmed0/youtube-uploader#119]
After some days of good working uploader the process does not longer work. If I start the upload script it stops at the youtube login screen with the following error message "**This browser or app may not be secure. Learn more Try using a different browser. If you’re already using a supported browser, you can try again to sign in.**".

Does anyone know how to solve it?

**Comment by Chipped1** [comment]
Having the same issue here (Ubuntu 22), seems to be google's anti-bot measures?

**Comment by TomixUG** [comment]
Same, I am running recently updated Arch Linux
