### ISSUE TITLE
Stuck at title filling

### ISSUE THREAD

**Issue by Qualzz** [fawazahmed0/youtube-uploader#120]
Hello, I have an issue. 

The upload completes, but the process stops at inputing the title. nothings happens from there.  ( it doesn"t even try ) 

It just correclty selecting the title input box, but then nothing. 

![image](https://user-images.githubusercontent.com/35169816/176981385-53fc4bfb-52e0-47bb-bcb5-a59250185e30.png)

Seems to happen randomly, anyone else having this issue ? 

( using headless: false ) if this information can be usefull

**Comment by sacredrel1c** [comment]
i have randomly this issue too, and pull request to fix this.

**Comment by murqlegend** [comment]
How did you fix this problem please help me

**Comment by fawazahmed0** [comment]
This Should be fixed in latest version, please open a new issue if the issue still persists
