### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by thomasssssssssssss** [fawazahmed0/youtube-uploader#121]
I'm getting this issue when I try to use the script. I followed the instructions exactly.

![image](https://user-images.githubusercontent.com/107980436/177012393-f267d652-dec8-4a28-a851-d5198ff72780.png)

**Comment by TomixUG** [comment]
Remove this line `import { upload } from 'youtube-videos-uploader' //Typescript`
After that there should be this line `const { upload } = require('youtube-videos-uploader'); //vanilla javascript`

Both lines import the library, but the first one only works in typescript or in ES6.

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to youtube-uploader@datascraping.pp.ua
