### ISSUE TITLE
file chooser failed on github actions (ubuntu-latest)

### ISSUE THREAD

**Issue by naptestdev** [fawazahmed0/youtube-uploader#130]
I got this error when run it in github actions environment. But it worked well on my mac air m1
<img width="916" alt="image" src="https://user-images.githubusercontent.com/88878684/178130820-bb7c3d4c-f029-45fd-b788-d67610f71f65.png">

**Comment by fawazahmed0** [comment]
This Should be fixed in latest version, please open a new issue if the issue still persists
