### ISSUE TITLE
Handling wrong file path

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#146]
If we happen to send a wrong file path, the program is stuck on this page :
![image](https://user-images.githubusercontent.com/35456349/182228235-a0825d25-6791-4ea9-af61-a116a2baaa12.png)
We could probably check for file existence before launching the launch, or look for the file unreadable error.
Or maybe even both ? I'd guess the unreadable file error might get thrown as well if the video is corrupted ?

**Comment by picola07** [comment]
i got the same error did anyone figured it out yet ?

**Comment by picola07** [comment]
I'am sure I used a right path I copied it by using shit and right click then I just paste it, I changed the file so many times and when I uploaded em manually and everything goes well I even changed format from mp4 to mkv and still have the same problem

**Comment by pierreminiggio** [comment]
Sorry to be repeating myself, but please check again that you're actually passing a local file path to a correct file, it's very likely that it's on your end.
There is a really small chance that Youtube could be having an issue, but on a feature as important as the file upload, I don't believe it would go without fix for more than a few hours. So very unlikely.

As you can see here, there is no process done in that library when it comes to the file path, it's straight up fed into the input file.
github.com/fawazahmed0/youtube-uploader/blob/0339fa6bb8fcf854782ec950ef0ff8168e441581/src/upload.ts#L82-L147

**Comment by pierreminiggio** [comment]
>... or look for the file unreadable error.

Here is an MR to close the program and throw an error if Youtube shows us an error.
This will cover the "You file could not be found or read" error in my issue, but it might also cover some other errors Youtube could show us that I'm not aware of : https://github.com/fawazahmed0/youtube-uploader/pull/155

**Comment by pierreminiggio** [comment]
> I'am sure I used a right path I copied it by using shit and right click then I just paste it, I changed the file so many times and when I uploaded em manually and everything goes well I even changed format from mp4 to mkv and still have the same problem

IDK if you found what you did wrong with your file path.
But I noticed something, while using an asbolute path that has a few "../", it failed.
So make sure to pass your file pathes into formatting functions to remove all the "../".
