### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by genso05** [fawazahmed0/youtube-uploader#147]
How do I use this code, can someone explain bit by bit. I hope someone will help me thanks so much

**Comment by pierreminiggio** [comment]
[Everything is in the README.md](https://github.com/fawazahmed0/youtube-uploader/blob/main/README.md)

**Comment by pierreminiggio** [comment]
@fawazahmed0 I think you can close this

**Comment by fawazahmed0** [comment]
Thanks @pierreminiggio
