### ISSUE TITLE
Publish time

### ISSUE THREAD

**Issue by pc11000** [fawazahmed0/youtube-uploader#148]
Hi! 
Is it possible to set the publish time of a video with this lib?

**Comment by pierreminiggio** [comment]
It currently is not a feature. But you could work on a merge request to make it happen :D

**Comment by pierreminiggio** [comment]
I think this issue should be closed, because it duplicates this one https://github.com/fawazahmed0/youtube-uploader/issues/64

**Comment by fawazahmed0** [comment]
Thanks @pierreminiggio ,  duplicate https://github.com/fawazahmed0/youtube-uploader/issues/64

**Comment by fawazahmed0** [comment]
@pc11000 You can create a PR, I will be happy to merge it
