### ISSUE TITLE
Throw on upload limit reached

### ISSUE THREAD

**Issue by pierreminiggio** [fawazahmed0/youtube-uploader#150]
I don't think reaching the upload limit should be a simple log, we should probably throw a documented exception after closing the browser

https://github.com/fawazahmed0/youtube-uploader/blob/db8c5b14f655b105d7ab89b67d8b186fd1822b9e/src/upload.ts#L171-L174

**Comment by PeterStegarus** [comment]
I've also noticed the 0.5 seconds timeout is too short on some occasions. 2 seconds did the trick for me but we should probably handle this some other way. Unsure if waiting indefinitely for 'Upload complete' is what we want

Maybe we could `Promise.race` the selectors for both the 'Daily upload limit' and 'Upload complete' elements. Will have to look further into this

https://github.com/fawazahmed0/youtube-uploader/blob/c34d632d852c4210855a7fdc014413eb40301021/src/upload.ts#L176

**Comment by fawazahmed0** [comment]
I guess this should be closed with [this PR](https://github.com/fawazahmed0/youtube-uploader/pull/163)
