### ISSUE TITLE
file unreadable 

### ISSUE THREAD

**Issue by picola07** [fawazahmed0/youtube-uploader#151]
anyone know this solution for this error ?
![image](https://user-images.githubusercontent.com/99802423/183533575-015cb06a-61c9-4d3b-b5df-7ec828c48fa3.png)

**Comment by pierreminiggio** [comment]
Duplicates https://github.com/fawazahmed0/youtube-uploader/issues/146
And I answered here : https://github.com/fawazahmed0/youtube-uploader/issues/146#issuecomment-1210625934
