### ISSUE TITLE
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises

### ISSUE THREAD

**Issue by AdeptOreo** [fawazahmed0/youtube-uploader#153]
I get this error: `Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises` when I try to run `const { upload } = require('youtube-videos-uploader');`
My node version is `v16.16.0`. How do I fix this error?

**Comment by pierreminiggio** [comment]
Why do you use the CommonJS module loader / require ?
Are you in a project that forces you to do that ?

You're better off using ES modules by adding
```
"type": "module"
```
in your package.json and using the `import` keyword instead, just like it's shown in the README.md.

**Comment by davidgalarza** [comment]
I'm facing the same issue after upgrading my node version to the latest LTS version

**Comment by RDKclick** [comment]
The solution is to switch Node version to 18.7.0 (Node needs to support readline/promises - API)

Readline/Promises was released after version 17.0

**Comment by Un1xMida** [comment]
to be honest this is a bad approach because this node version (18.7.0) is the current version which is NOT good to use because we will run into problems the better approach is to use the LTS version.

**Comment by RDKclick** [comment]
16.17.0-LTS version has no Readline/Promises.Perhaps you can change the code to use readline other methods instead.

**Comment by pierreminiggio** [comment]
Readline is likely gonna get removed via this MR : https://github.com/fawazahmed0/youtube-uploader/pull/157

**Comment by fawazahmed0** [comment]
Please see [this](https://github.com/fawazahmed0/youtube-uploader/pull/157#issuecomment-1226032833)
