### ISSUE TITLE
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:readline/promises

### ISSUE THREAD

**Issue by Un1xMida** [fawazahmed0/youtube-uploader#156]
after installing the new version iam getting this error, sorry but i got no time to trace it down.
youtube-videos-uploader version is ^1.3.78

**Comment by Un1xMida** [comment]
i think it something related to the node version so here is my node version :16.10.0

**Comment by pierreminiggio** [comment]
Duplicates https://github.com/fawazahmed0/youtube-uploader/issues/153
