### ISSUE TITLE
Videos default to "Made for Kids" even when using the right arguments

### ISSUE THREAD

**Issue by suhailidrees** [fawazahmed0/youtube-uploader#217]
I'm using the following tags:

isAgeRestriction: false
isNotForKid: false

but the videos are still getting uploaded as "Made for Kids".

The channel default is also set to "No, set this channel as not made for kids. I never upload content that's made for kids." (rather than "I want to review this setting for every video")

```
const video1 = {
        path: ...,
        title: ...,
        description: ...,
        isAgeRestriction: false, 
        isNotForKid: false,
    }

    // Returns uploaded video links in array
    upload (credentials, [video1]).then((videoUrl) => {
        console.log("success");
        console.log(videoUrl);
    }).catch((err) => {
        console.log(err)
    })
```

The console log does print "success" and the videoUrl, so the request is completing successfully (and I can see the video has been uploaded)

**Comment by pierreminiggio** [comment]
The variable is named "isNotForKid", which means that if you set it as "false", the video is then for kids.
Because double negative is positive.
So according to the variable names, it seems that you're using it wrong, maybe try again with "isNotForKid" set as "true".

**Comment by suhailidrees** [comment]
That makes sense. I'll try it when I get a chance (ran into my upload limit...)

I'd suggest making the naming simpler, i.e. "madeForKids".

I'll close the issue for now.

**Comment by pierreminiggio** [comment]
I'm not sure how and why we ended up with that name.
I personnally would never name booleans with negative names exactly for that reason ahah
