### ISSUE TITLE
Waiting for processing 

### ISSUE THREAD

**Issue by TentacleSama4254** [fawazahmed0/youtube-uploader#27]
For slightly longer videos (>1hour) the programme stops after uploading the video and thumbnail without entering the rest of the info (promt:'video upload complete, processing will begin shortly'). 

Eventually the programme times out without entering in the rest of the info and the video goes into draft

I think it's good to add a another route to enter in the info if the waiting takes too long and let youtube finish the processing later

**Comment by fawazahmed0** [comment]
I have uploaded videos of around 1 hour 20min length, and it worked fine, can you share your video, so that I could look

**Comment by TentacleSama4254** [comment]
> I have uploaded videos of around 1 hour 20min length, and it worked fine, can you share your video, so that I could look

Yeah nvm, I removed the line that awaits the processing and added a 5s timeout after upload. So the video will upload with the info and the processing will fi ish later

**Comment by fawazahmed0** [comment]
Please send a PR, I will merge it, as it solved your problem

**Comment by TentacleSama4254** [comment]
#57
