### ISSUE TITLE
can you add support for private videos?

### ISSUE THREAD

**Issue by TomerGamerTV** [fawazahmed0/youtube-uploader#28]
as the title says

**Comment by fawazahmed0** [comment]
In your youtube upload defaults, set Visibility to Private

![Screenshot (190)](https://user-images.githubusercontent.com/20347013/128909616-b64eaf52-c725-43d4-8dc2-da1bf218ddc2.png)

**Comment by TomerGamerTV** [comment]
> In your youtube upload defaults, set Visibility to Private
> 
> ![Screenshot (190)](https://user-images.githubusercontent.com/20347013/128909616-b64eaf52-c725-43d4-8dc2-da1bf218ddc2.png)

I'm a little new to it so can you give me an example command or batch file?

**Comment by pierreminiggio** [comment]
If you want every video you upload to be set as private, you can set up **on your Youtube account** your default visibility to be private, as @fawazahmed0 showed above.

**Comment by TomerGamerTV** [comment]
> If you want every video you upload to be set as private, you can set up **on your Youtube account** your default visibility to be private, as @fawazahmed0 showed above.

i mean an example batch files to upload every single video from a folder without giving them names

**Comment by pierreminiggio** [comment]
You can do that in JavaScript, you can use the "fs" API to read files from a folder, and then upload them using this package.
You'll have to build a video title yourself that could as an exemple simply be the file name.
