### ISSUE TITLE
New Feature : onSuccess function, as an optional argument in videoConfig

### ISSUE THREAD

**Issue by charan0017** [fawazahmed0/youtube-uploader#31]
Requesting for the feature for onSuccess function

I need to perform some tasks on each video after its upload is complete.
As videos are uploaded in bulk and then it will return all the video Links.
So I need to wait for all videos the complete the upload process and then perform my tasks on each uploaded video link.
The problem comes with the `Waiting Time`.
Since I was uploading huge videos (each video length is 3 to 4 hrs), so let's say I upload 10 videos, and with my moderate internet speed, it takes around 2hrs. But in the meantime, if my internet goes off, the whole process is dismissed.

So, you can implement an optional option of `onSuccess`, which is  `'function'` type.
And you can check and run it at the end of each video upload complete, however, you may have to provide the Uploaded `videoUrl` as an argument to the `onSuccess(videoUrl)` function.
Also, you can leave it if the argument is not the required type (function).
And also, you can 

`Before`
```js
const onVideoUploadSuccess = (videoUrl) => {
    // ..do something..
}

const videoConfig1 = { path: 'video1.mp4', title: 'title 1', description: 'description 1' }
.
.
const videoConfig200 = { path: 'video2.mp4', title: 'title 2', description: 'description 2' }

const videoUrls = await upload(credentials, [videoConfig1, .., videoConfig200], puppeteerConfig)

for (const videoUrl of videoUrls) {
    onVideoUploadSuccess(videoUrl);
}
console.log('Done!');
```

`After`
```js
const onVideoUploadSuccess = (videoUrl) => {
    // ..do something..
}

const videoConfig1 = { path: 'video1.mp4', title: 'title 1', description: 'description 1', onSuccess: onVideoUploadSuccess  }
.
.
const videoConfig200 = { path: 'video2.mp4', title: 'title 2', description: 'description 2', onSuccess: onVideoUploadSuccess }

await upload(credentials, [videoConfig1, .., videoConfig200], puppeteerConfig)
console.log('Done!');
```

**Comment by fawazahmed0** [comment]
Please create a PR, I will be happy to merge it

**Comment by charan0017** [comment]
> Please create a PR, I will be happy to merge it

Okay, its done: https://github.com/fawazahmed0/youtube-uploader/pull/32

You can now merge
And also can update Readme and publish to npm

Close the issue once its done, so that I can install the new update 😊

**Comment by fawazahmed0** [comment]
Thanks for the PR, I will test your PR & merge it by today, in my free time.

Thanks once again for your PR 👍
