### ISSUE TITLE
question

### ISSUE THREAD

**Issue by elpidios** [fawazahmed0/youtube-uploader#35]
Hi my friend
I will try your youtube uploader. I have made through API but unfortunately i get error, that the terms & conditions are violated. I believe is because my upload app is unverified. WIth yours i will have that issue?

**Comment by fawazahmed0** [comment]
No, you will not have that issue

**Comment by elpidios** [comment]
great. would you like to exchange whatsapp please? I have created a wordpress plugin for e-commerce website which takes the photos from the products and automatically create videos. Then we upload it automatically to youtube. I believe the integration with your software it will have very good results. If you would like to exchange contacts to see if we can make that script to work very well it will be great and to get advantages
