### ISSUE TITLE
install jsnode & script

### ISSUE THREAD

**Issue by elpidios** [fawazahmed0/youtube-uploader#36]
Hi
I have establish to install jsnode. I don't know where to run the code provided in your instructions. How can i run it? I am in the terminal i am doing node upload.js but not working. I am doing for sure something wrong. Please give more begginer instructions

**Comment by elpidios** [comment]
I have also try to donate your project but gives me an error if i am try to paypal. Please give me a contact way to contact you and help me to configure it with a payment & donation.

**Comment by fawazahmed0** [comment]
Hi, you can hire a developer from sites such as [upwork ](https://www.upwork.com/)or [freelancer ](https://www.freelancer.com/) to help you out.

Thanks
