### ISSUE TITLE
Can you make small video about "How to run?"

### ISSUE THREAD

**Issue by chamanbabangogo** [fawazahmed0/youtube-uploader#44]
I am new to working with nodes/tool/cmd
Can you please make very small basic video regarding how to run script.. specially the "Usage" section
this will help a lot to get things going forward!

Thanks

**Comment by chamanbabangogo** [comment]
screenshots will also work

**Comment by weizhiqimail** [comment]
maybe cannot, because video will show google email, we can cover some sensitive messages, but it's troublesome. All actions are same as your normal actions.

**Comment by fawazahmed0** [comment]
This video may help:
https://www.youtube.com/watch?v=900uz583XAQ

**Comment by chamanbabangogo** [comment]
Consol showing this message:


(node:8704) UnhandledPromiseRejectionWarning: Error: Lang menu item selector not found : TimeoutError
    at changeHomePageLangIfNeeded (C:\Users\Administrator\node_modules\youtube-videos-uploader\upload.js:196:11)
    at async upload (C:\Users\Administrator\node_modules\youtube-videos-uploader\upload.js:110:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8704) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substring' of undefined
    at uploadVideo (C:\Users\Administrator\node_modules\youtube-videos-uploader\upload.js:375:33)
    at async upload (C:\Users\Administrator\node_modules\youtube-videos-uploader\upload.js:113:18)
(node:8704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by susantha1995** [comment]
> Thanks for the link, it helped to get this moving ahead
> 
> EDIT 5
> 
> It was a success!

can you give me little tutorial to run this script ?
