### ISSUE TITLE
Better debug messages

### ISSUE THREAD

**Issue by fawazahmed0** [fawazahmed0/youtube-uploader#45]
Print better debug/error messages, so that user can easily understand the issue & solve it

**Comment by TueNguyen2911** [comment]
I'd like to work on this issue, please. Thank you!

**Comment by fawazahmed0** [comment]
Hi @TueNguyen2911 , I have assigned this task to you, code is in [upload.js](https://github.com/fawazahmed0/youtube-uploader/blob/main/upload.js)

**Comment by TueNguyen2911** [comment]
Thank you, I will look into it

**Comment by TueNguyen2911** [comment]
Hi @fawazahmed0, I took a look but most error messages addressing user's input are clear. Please unassign me from the task

**Comment by TueNguyen2911** [comment]
Hi, thank you for your instructions, I took a look again and submitted a PR.
