### ISSUE TITLE
TypeError: tags.join is not a function

### ISSUE THREAD

**Issue by zhchhua** [fawazahmed0/youtube-uploader#61]
when I  upload the videos more than six hours, it reports error as following :
(node:3864213) UnhandledPromiseRejectionWarning: TypeError: tags.join is not a function
    at /home/zch/node_modules/youtube-videos-uploader/dist/upload.js:175:57
    at Generator.next (<anonymous>)
    at fulfilled (/home/zch/node_modules/youtube-videos-uploader/dist/upload.js: 5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3864213) UnhandledPromiseRejectionWarning: Unhandled promise rejection. Th                        is error originated either by throwing inside of an async function without a cat                        ch block, or by rejecting a promise which was not handled with .catch(). (reject                        ion id: 1).It can only upload one vidow as draft,How can I fix this,Thanks for answering.

**Comment by Un1xMida** [comment]
you need to pass the tags as array of strings 
example 
`tags:["tag1","tag2","tag3"]`
