### ISSUE TITLE
Does this use random useragent and screen resolution?

### ISSUE THREAD

**Issue by Zebraslive** [fawazahmed0/youtube-uploader#63]
Does this puppeteer script use random useragent and random screen resolution?

**Comment by fawazahmed0** [comment]
You can pass all puppeteer launch options
```
// This package uses Puppeteer, you can also pass Puppeteer launch configuration
upload (credentials, [video1, video2], {headless:false}).then(console.log)
```
This package uses [puppeteer-extra-plugin-stealth](https://www.npmjs.com/package/puppeteer-extra-plugin-stealth) to prevent detection.
