### ISSUE TITLE
Heroku support 

### ISSUE THREAD

**Issue by TentacleSama4254** [fawazahmed0/youtube-uploader#70]
I tried to use this repo in a heroku app, but in heroku puppeteer seem to require the puppeteer buildpack wich is 250mb-ish https://github.com/jontewks/heroku-buildpack-puppeteer-firefox

But after using that the slug size goes over 500mb to about 570 mb wich cannot be used in the free dyno

Do you know any solution 🤔

**Comment by fawazahmed0** [comment]
I used heroku only once, so I don't know much about it
