### ISSUE TITLE
"This browser or app may not be secure" error on login

### ISSUE THREAD

**Issue by alumbo** [fawazahmed0/youtube-uploader#72]
Google login is not blocked on Chromium, any workaround?

**Comment by Un1xMida** [comment]
is blocked u mean right ?

**Comment by Un1xMida** [comment]
@alumbo is u mean that the login is blocked i have had the exact same problem and i've bypassed it.

**Comment by augustwu** [comment]
> @alumbo is u mean that the login is blocked i have had the exact same problem and i've bypassed it.

May I ask how to bypassed it?
Which code did it ?

**Comment by fawazahmed0** [comment]
This is already fixed in latest version
