### ISSUE TITLE
Major problems with Brand Accounts.

### ISSUE THREAD

**Issue by asppect** [fawazahmed0/youtube-uploader#74]
As the title says your unable to automate switching to a brand account due to them not showing up on the [channel_switcher](https://www.youtube.com/channel_switcher) page. You can, however, switch to a brand account still by manually clicking on your avatar and going to "Switch Account" due to upload.js clicking on elements that have "channelname" in it. 

However that isn't where the issues end, when I'm on the brand account I get booted off when I'm redirected to the upload page, the upload still goes on though which causes the upload to be done on the wrong account which is pretty annoying.

**Comment by fawazahmed0** [comment]
> @fawazahmed0 i can create an pr with a hot fix for this fix.

Yeah, go ahead, I will merge the PR
