### ISSUE TITLE
Can i hide the webdriver- browser each uploading?

### ISSUE THREAD

**Issue by altagalgi** [fawazahmed0/youtube-uploader#75]
Hope can find a solution
thank you

**Comment by Un1xMida** [comment]
what do u mean ? did u mean that u need to hide the browser in the uploading cycle ?

**Comment by altagalgi** [comment]
> what do u mean ? did u mean that u need to hide the browser in the uploading cycle ?

exactly. its possible right?

**Comment by Un1xMida** [comment]
yeah sure 
`upload(credentials, videos, { headless: false}).then(console.log).catch(error => console.log('ERROR FOUND'));
`add this headless: true
