### ISSUE TITLE
To continue your session, complete a brief verification.

### ISSUE THREAD

**Issue by Un1xMida** [fawazahmed0/youtube-uploader#76]
iam getting this error when am trying to start the uploader from rdp client 
i have no idea what is the problem here.

full error message: `To continue your session, complete a brief verification. This extra step helps us keep your account safe by making sure it’s really you.`

**Comment by Un1xMida** [comment]
hello @fawazahmed0 i just found this 
![image](https://user-images.githubusercontent.com/10745789/155048753-8420db82-b65d-4320-9066-c36193018cc7.png)
on my rdp 

maybe this is the problem

**Comment by Un1xMida** [comment]
i managed to bypass it and iam running a expermenting cycle to get to know why i faced this issues before.

**Comment by fawazahmed0** [comment]
Yeah, please create a PR, I will be happy to merge it

**Comment by Un1xMida** [comment]
@fawazahmed0 after a lot of investigations when somebody gets this error remove the yt_auth folder then re run the uploading cycle :) that will bypass it.

**Comment by Un1xMida** [comment]
please consider adding it in the docs and close the questions related to it good luck brother :) @fawazahmed0

**Comment by fawazahmed0** [comment]
Thanks @Un1xMida

**Comment by Un1xMida** [comment]
most welcome buddy keep up the good work.
