### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by MicroChip321** [fawazahmed0/youtube-uploader#78]
This no longer bypasses the limit from my own experimenting,
is it possible for you to fix this?

**Comment by Un1xMida** [comment]
@MicroChip321 what do u mean ?

**Comment by MicroChip321** [comment]
This doesn't seem to bypass the daily upload limit anymore. I'm not sure why, but whenever I hit my upload limit it stops

**Comment by MicroChip321** [comment]
> @MicroChip321 what do u mean ?

**Comment by MicroChip321** [comment]
Also, @fawazahmed0 I know this is out of topic, but I was wondering if you could check your hotmail? I sent you a project a friend made for me that almost uses everything you have made, but it has some issues, and I was wondering if you could take a look at the email.

**Comment by Un1xMida** [comment]
> Also, @fawazahmed0 I know this is out of topic, but I was wondering if you could check your hotmail? I sent you a project a friend made for me that almost uses everything you have made, but it has some issues, and I was wondering if you could take a look at the email.

do u mean that ur friend used this package to create a project but you are facing issue right now ?

**Comment by MicroChip321** [comment]
yep
