### ISSUE TITLE
I need help with a project of mine.

### ISSUE THREAD

**Issue by MicroChip321** [fawazahmed0/youtube-uploader#79]
Hello, firstly I apolgize if this is not the right way to get in contact with you, I've tried emailing but I'm not sure if you have gotten them. A friend of mine made me a node script in which I fill in the followings, 
**YouTube Email address:
YouTube password:
YouTube Channel Name:
Video Location on your computer:
Video Title:
Video Description:
Upload amount:
Upload wait Time (in seconds):**
^ everything above is self explanatory, once I fill in these fields it will start uploading the same video over and over, the main thing is that it bypasses the youtube upload limit, I am a noob when it comes to coding and I know NOTHING, my friend who coded this for me uses almost everything from @fawazahmed0 's project. we both ran into an issue, the uploader does not bypass youtube's limit. sometimes on rare ocasions it works, but majority of the time it will not work once it reaches youtube's limit,, 
https://www.mediafire.com/file/my5n05c0czi5p4a/auto-upload.zip/file I have provided the file my friend coded to me here, and I was wondering if you could take a look at it? maybe we did something wrong, your help and knowledge on this would be greatly appreciated.

this is the error I get
(node:10644) UnhandledPromiseRejectionWarning: Error: Node is either not clickable or not an HTMLElement
    at ElementHandle.clickablePoint (C:\Users\Dawood\Desktop\YT\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:408:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ElementHandle.click (C:\Users\Dawood\Desktop\YT\node_modules\puppeteer\lib\cjs\puppeteer\common\JSHandle.js:492:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:10644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fawazahmed0** [comment]
I am not sure, if I could help, the issue might be with my package itself. If you can fix the issue, please also create a PR, so that others can benefit from it.
