### ISSUE TITLE
Single Quotes in playlist name. 

### ISSUE THREAD

**Issue by DominicFindlay** [fawazahmed0/youtube-uploader#80]
Having an issue where it cannot find an existing playlist which has a single quote in it's name. (Possibly may have same issue with other fields?). 

I have tried looking this up, but not really sure if there's anything simple I can do to change the string, tried `/'` `''` , or is this just a limitation of `xPath` or `js` in general?

**Comment by fawazahmed0** [comment]
try escaping the quote something like this  `\'`

**Comment by DominicFindlay** [comment]
Hi, Yeah I've tried that.

This is the error message that I got it to print out

`Error: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string '//*[normalize-space(text())='Name\'s Driving']' is not a valid XPath expression.`

Where Playlist name is `Name's Driving`

**Comment by fawazahmed0** [comment]
Please refer [this](https://stackoverflow.com/a/14822893) you might need to use concat function or something else.
Also if you can create a PR to fix this issue, I will be happy to merge it.
