### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by colinvinson** [fawazahmed0/youtube-uploader#81]
I’m a youtuber looking to automate my uploads but i'm new to GitHub and pretty inexperienced with this kinda stuff. I installed Nodejs and ran the command “npm I youtube-videos-uploader”… but now I’m stuck. I tried running commands such as import, const, etc, in my command prompt but it keeps saying command not recognized. Again, forgive me if I sound stupid, I’m trying to figure all this out. If someone could help me set this up it would mean a ton!

**Comment by susantha1995** [comment]
> I’m a youtuber looking to automate my uploads but i'm new to GitHub and pretty inexperienced with this kinda stuff. I installed Nodejs and ran the command “npm I youtube-videos-uploader”… but now I’m stuck. I tried running commands such as import, const, etc, in my command prompt but it keeps saying command not recognized. Again, forgive me if I sound stupid, I’m trying to figure all this out. If someone could help me set this up it would mean a ton!

did you find a way to run this script? can you tell me how to use this script?
