### ISSUE TITLE
TimeoutError: waiting for XPath 

### ISSUE THREAD

**Issue by salman0ansari** [fawazahmed0/youtube-uploader#83]
`TimeoutError: waiting for XPath //[normalize-space(text())='Publish']/parent::[not(@disabled)] | //[normalize-space(text())='Save']/parent::[not(@disabled)] failed: timeout 60000ms exceeded`

**Comment by salman0ansari** [comment]
any fix? @fawazahmed0

**Comment by Un1xMida** [comment]
this bug is related to many puppeteer scripts 
code u please stop the script and run it again and make sure to add headless: false to the upload method to inspect what is happening and just let me know?

**Comment by lindatateam** [comment]
I got the same issue, even adding headless as false
<pre>
.../node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528
const timeoutError = new Errors_js_1.TimeoutError(`waiting for ${options.title} failed: timeout ${options.timeout}ms exceeded`);

TimeoutError: waiting for XPath `//*[normalize-space(text())='Publish']/parent::*[not(@disabled)] | //*[normalize-space(text())='Save']/parent::*[not(@disabled)]` failed: timeout 60000ms exceeded

</pre>

**Comment by fawazahmed0** [comment]
Should be fixed in latest version, please open a new issue if the issue still persists
