### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by susantha1995** [fawazahmed0/youtube-uploader#84]
hi, please can you give me step by step simple guide to run this script? after running npm i youtube-videos-uploader what to do? where to enter others?

**Comment by susantha1995** [comment]
hi, please ANYONE can make a short how-to video or screenshots to install and use this script correctly? this is hard to understand beginners.

**Comment by ImAqux** [comment]
hey have you figured it out ?

**Comment by susantha1995** [comment]
> hey have you figured it out ?

nope. I have basic knowledge about this, I installed nodejs and used this command npm i youtube-videos-uploader and that's it. i can't find exactly which files to edit or run to work this script. Please can make a little video tutorial or some step-by-step screenshots to make this happen for very beginner? 
thank you very much!

**Comment by Koroneiki** [comment]
yes please help i dont understand how to continue after installing, because i dont know how to run this script.

**Comment by Un1xMida** [comment]
guys i can help with it 
just tell me how to do so and i will help u through it .

**Comment by Un1xMida** [comment]
install the lib via : **npm i youtube-videos-uploader**
create your **index.js** file
then paste this code and add your **credentials** then add your **videos array** 
save the file 
in the terminal run "**node index.js**"
enjoy .... :)
`const { upload } = require("youtube-videos-uploader");

const credentials = {
  email: "YOUR_ACCOUNT",
  pass: "YOUR_PASSWORD",
  recoveryemail: "YOUR_RECOVERY_MAIL",
};
upload(credentials, videosList).then(console.log);

`

**Comment by Un1xMida** [comment]
`asdasd`

**Comment by wakeuplz** [comment]
> 

Thank you so much !! i am beginners and trying to run this .Also I have a question ,can i upload multiply videos at the same time by this script? thank you sir !

**Comment by susantha1995** [comment]
> videos array

what do you mean by "add your videos array"? how to select local computer videos files and video titles, descriptions,s, and other things? can you explain that part more, please?

**Comment by Un1xMida** [comment]
> > 
> 
> Thank you so much !! i am beginners and trying to run this .Also I have a question ,can i upload multiply videos at the same time by this script? thank you sir !

well yeah u can use it with wokers or something

**Comment by Koroneiki** [comment]
@Un1xMida 
So i've used your code and put my credentials and video paths and everything in, but when i run the script, it logs into my youtube account but then just returns the following:

This Channel already exists or there was an error creating the channel.
Session has been successfully saved.

**Comment by Un1xMida** [comment]
add me on discord Un1xCr3w#6724 lets fix some bugs :)

**Comment by faderzz** [comment]
> @Un1xMida So i've used your code and put my credentials and video paths and everything in, but when i run the script, it logs into my youtube account but then just returns the following:
> 
> This Channel already exists or there was an error creating the channel. Session has been successfully saved.

Have you managed to fix it?

**Comment by tamon504** [comment]
i tried this script create one index.js like mentioned earlier but facing error like this.? any help please

C:\nodejs\node_modules\index.js:10
const { upload } = require("youtube-videos-uploader");
        ^

SyntaxError: Identifier 'upload' has already been declared
←[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by tamon504** [comment]
anyone please help a detailed step by step after install the lib via : npm i youtube-videos-uploader
i tried several time using the code above facing error...i dont know how to do

**Comment by tamon504** [comment]
anyone know how to bypass the 10 daily limit.? i tried but after 10 videos the upload process wonk continue

**Comment by thomasssssssssssss** [comment]
> add me on discord Un1xCr3w#6724 lets fix some bugs :)

I added you my brother. Please help me
