### ISSUE TITLE
how can i fix this and run the scipt ? plz help !!

### ISSUE THREAD

**Issue by wakeuplz** [fawazahmed0/youtube-uploader#87]
![image](https://user-images.githubusercontent.com/102350336/160103203-38a01be2-6968-429c-a8d9-d12e406e143f.png)

**Comment by wakeuplz** [comment]
![image](https://user-images.githubusercontent.com/102350336/160101188-03fff9a3-740d-4d55-97c8-5f929bf657a3.png)

**Comment by wakeuplz** [comment]
i fix that and met this 😥😥

**Comment by wakeuplz** [comment]
I now can run the script but it cannot upload the video in my drive on pc

**Comment by wakeuplz** [comment]
yssssss!!!! i slove the problem , i use / instead of \ and work really well !!!

**Comment by pierreminiggio** [comment]
You could click the "close issue" button since your problem is solved ;)
