### ISSUE TITLE
I HAVE A QUESTION : How can i upload 100 video at the same time ? 

### ISSUE THREAD

**Issue by wakeuplz** [fawazahmed0/youtube-uploader#88]
I need to add 100 video in the code file ? or have a convenient way? thank you

**Comment by Un1xMida** [comment]
yeah u can use it with promise.all

**Comment by DuckySoLucky** [comment]
Can I get an example of that? Please ;-;

**Comment by k3fjeee** [comment]
> yeah u can use it with promise.all @Un1xMida 


Hi. How should I do it?
