### ISSUE TITLE
Upload video successfully but got error

### ISSUE THREAD

**Issue by augustwu** [fawazahmed0/youtube-uploader#89]
Hello
I can upload video successfully but still get error , anyone can help?
Thanks
C:\Users\Administrator\Documents\ytb\node_modules\youtube-videos-uploader\dist\upload.js:273
            throw new Error('Please make sure you set up your default video visibility correctly, you might have forgotten. More infos : https://github.com/fawazahmed0/youtube-uploader#youtube-setup');
                  ^

Error: Please make sure you set up your default video visibility correctly, you might have forgotten. More infos : https://github.com/fawazahmed0/youtube-uploader#youtube-setup
    at C:\Users\Administrator\Documents\ytb\node_modules\youtube-videos-uploader\dist\upload.js:273:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Documents\ytb\node_modules\youtube-videos-uploader\dist\upload.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by augustwu** [comment]
Below is my setting
![微信图片_20220401172023](https://user-images.githubusercontent.com/720069/161235206-fd266814-546c-49cd-9379-82aad2bff8f1.png)

**Comment by fawazahmed0** [comment]
Should be fixed in latest version, please open a new issue if the issue still persists
