### ISSUE TITLE
Daily Upload Limit???

### ISSUE THREAD

**Issue by Koroneiki** [fawazahmed0/youtube-uploader#90]
So, i've uploaded a few videos using this script.
But after only 8 videos uploaded, the script always timeouted with an error and the youtube url.
That was with `upload (credentials, [video1, video2]).then(console.log)`
When using `upload (credentials, [video1, video2], {headless:false}).then(console.log)` the script starts in Chromium and you can see what's going on and the problem was easy to notice.
The daily upload limit was reached, despite the channel using only just being created today and only having 8 total videos i uploaded today.
On the Readme it says "No upload Limits (50+ videos/day limit set by youtube for every channel)". 
Huh, i dont understand, why i cant upload more???

**Comment by Koroneiki** [comment]
I've verified my phone number and could upload 10 more videos. Then I hit the upload limit again...

**Comment by RAY-EZ** [comment]
Youtube allows you to upload more than 50 videos once you have done verification with ID. 
Verifying with phone number will give you intermediate access, for advance features you need id verification. 
[read here](https://support.google.com/youtube?p=advanced_features4)

**Comment by fawazahmed0** [comment]
You can upload less than 100 videos per day, if you do more, then you will be blocked for sometime.
So always try to keep your daily uploads less than 100
