### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by akshatj27** [fawazahmed0/youtube-uploader#91]
Add support for uploading multiple videos at same time to make it faster.

**Comment by Koroneiki** [comment]
You can upload multiple videos at the same time:
`const videoslist = [
  {
      path: `demo-video.mp4`,
      title: "Video Title",
      description: `Video Description`,
      tags: ["tag1","tag2"],
  },
  {
      path: `demo-video2.mp4`,
      title: "Video Title",
      description: `Video Description`,
      tags: ["tag1","tag2"],
  },
  {
      path: `demo-video3.mp4`,
      title: "Video Title",
      description: `Video Description`,
      tags: ["tag1","tag2"],
  },
]`

**Comment by akshatj27** [comment]
@Koroneiki that doesnt upload them at the "same time", it uploads them one after the another

**Comment by Koroneiki** [comment]
well in that case you gonna make multiple *,js files with the videos you like and run a batch script which opens them simultaenously

**Comment by akshatj27** [comment]
> well in that case you gonna make multiple *,js files with the videos you like and run a batch script which opens them simultaenously

thats a workaround, This issue is a feature request. I'm not asking how to do it, i'm asking for it to be implemented in the library.

**Comment by fawazahmed0** [comment]
Paid support is available for quick resolution & help.

For paid support, please write mail to [youtube-uploader@datascraping.pp.ua](mailto:youtube-uploader@datascraping.pp.ua)
