### ISSUE TITLE
publish button is not working in last tab

### ISSUE THREAD

**Issue by prasaath6** [fawazahmed0/youtube-uploader#93]
publish button is not working in the last tab

if we upload shorts URL is changed like this "https://youtube.com" upload.js 249 and 250... please write the logic to handle URL change detect
```
yield page.waitForSelector('[href^="https://youtube.com"]');
const uploadedLinkHandle = yield page.$('[href^="https://youtube.com"]')
```

**Comment by murqlegend** [comment]
Hello,

Would just swapping 249 and 250 fix the problem for shorts?

254 of them: } while (uploadedLink === 'https://youtube.com/'); should we do?

**Comment by fawazahmed0** [comment]
This Should be fixed in latest version, please open a new issue if the issue still persists
