### ISSUE TITLE
hey, im unable to work this out, can you please help me ?

### ISSUE THREAD

**Issue by MxrseShitsOnYou** [fawazahmed0/youtube-uploader#95]

**Comment by Un1xMida** [comment]
yeah sure add me on discord Un1xCr3w#6724

**Comment by MxrseShitsOnYou** [comment]
I sent you a request on discord :)

**Comment by MxrseShitsOnYou** [comment]
As Mxrse

**Comment by dement6d** [comment]
- Install [Node.js](https://nodejs.org/en/download/)
- Create a new folder where your app will be located (example: upload-bot)
- Open cmd.exe, and navigate into that folder with the `cd` command (_example `cd Desktop/upload-bot` if you created the folder in your desktop and youre located in your user profile when you open cmd.exe which is where you would usually be unless you ran cmd.exe as an admin_)
- Once youre in the folder, create a new node project with this command :`npm init -y`, this will create a package.json file in the folder
- Install this package by doing `npm i youtube-videos-uploader`
- Create a new file called `index.js` in the `upload-bot` folder, this is the javascript file in which your code will be
- Paste the following code into that file
```js
const { upload } = require('youtube-videos-uploader');
const credentials = { email: 'YOURMAIL@gmail.com', pass: 'YOURPASS' }
const video = { path: "C:/Users/YOURNAME/Desktop/EXAMPLEVIDEO.mp4", title: "EXAMPLE VIDEO TITLE", description: "EXAMPLE DESCRIPTION" }

upload(credentials, [ video ], {headless: false}).then(console.log)
```
### OBVIOUSLY, you have to replace the example strings i put in place with your own email, video title and path etc...
#### If you want to hide the browser, remove `, {headless: false}` from the code

Once your code is ready, you can run the app by running the `node index.js` command in the cmd.exe (_or in the visual studio code terminal if you use visual studio code_) while youre in the `upload-bot` directory

### If you get an error that says "Channel already exists or there was an error creating the channel." you are possibly being prompted to enter a 2FA code when the app tries to log into your account
